/**
 * Generates docs/SCENE_LIBRARY.md and docs/STYLE_LIBRARY.md from the live
 * registries so the docs can never drift from the code.
 *
 *   npx tsx cli/gen-docs.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { SceneRegistry, type SceneCategory } from '../src/scenes/registry';
import '../src/scenes';
import { STYLE_PRESETS } from '../src/styles/presets';
import { TRANSITIONS } from '../src/transitions/presentations';
import { SFX, SFX_CATEGORIES } from '../src/audio/sfx-library';
import { ROOT } from '../src/node/workspace';

const docs = join(ROOT, 'docs');
mkdirSync(docs, { recursive: true });
const mods = SceneRegistry.list();
const cats = [...new Set(mods.map((m) => m.manifest.category))] as SceneCategory[];
const variants = mods.reduce((s, m) => s + m.manifest.variants.length, 0);

let md = `# Scene library\n\n_Generated from the SceneRegistry by \`npx tsx cli/gen-docs.ts\` — do not edit by hand._\n\n**${mods.length} families · ${variants} variants · ${cats.length} categories.** Every family works in 9:16, 16:9, 1:1 and 4:5 unless noted, validates its \`content\` with Zod, and ships an example used by the Studio and the visual-regression gallery.\n\n`;
md += `## Friendly aliases\n\n${SceneRegistry.aliasList().map(([a, id]) => `\`${a}\` → \`${id}\``).join(' · ')}\n\n`;
for (const c of cats) {
  const list = mods.filter((m) => m.manifest.category === c);
  md += `## ${c} (${list.length})\n\n| Family | Variants | Beats | Duration (s) | Content (required*) |\n|---|---|---|---|---|\n`;
  for (const m of list) {
    const x = m.manifest;
    const shape = (x.content as unknown as { shape?: Record<string, { isOptional?: () => boolean }> }).shape ?? (x.content as unknown as { _def?: { schema?: { shape?: Record<string, { isOptional?: () => boolean }> } } })._def?.schema?.shape;
    const fields = shape ? Object.entries(shape).map(([k, v]) => (v.isOptional?.() ? k : `${k}*`)).join(', ') : '—';
    md += `| **${x.id}**<br>${x.description} | ${x.variants.map((v) => (v === x.defaultVariant ? `**${v}**` : v)).join(', ')} | ${x.beats.join(', ')} | ${x.minDuration}–${x.maxDuration} (default ${x.defaultDuration}) | ${fields} |\n`;
  }
  md += '\n';
}
md += `## Transitions (${Object.keys(TRANSITIONS).length})\n\n${Object.values(TRANSITIONS).map((t) => `\`${t.id}\` (${t.label}, energy ${t.energy})`).join(' · ')}\n\n`;
md += `## Adding a scene family\n\n1. Create a module under \`src/scenes/<category>/\` exporting \`defineScene(manifest, Component)\`.\n2. Give it a Zod \`content\` schema, variants, durations, beats, SFX suggestions and an \`example\`.\n3. Export it from the group file (it is auto-registered by \`src/scenes/index.ts\`).\n4. Run \`npm test\` (manifest checks) and \`npm run gallery -- --only <id> --variants all\` to review it.\n5. Optionally add a Director recipe in \`src/director/recipes.ts\` so the Director can pick it.\n`;
writeFileSync(join(docs, 'SCENE_LIBRARY.md'), md);

let st = `# Style library\n\n_Generated by \`npx tsx cli/gen-docs.ts\`._\n\n**${Object.keys(STYLE_PRESETS).length} presets.** A style is a set of tokens (palette, type, surfaces, motion, transitions, textures). A brand profile (from a logo or user colours) overrides the palette; contrast is re-enforced after every override.\n\n| Style | Mode | Display / body font | Motion | Transitions | Description |\n|---|---|---|---|---|---|\n`;
for (const t of Object.values(STYLE_PRESETS)) st += `| **${t.id}**<br>${t.name} | ${t.mode} | ${t.typography.display} / ${t.typography.body} | ${t.motion.easing}, ${t.motion.entrance}, intensity ${t.motion.intensity} | ${t.transitions.join(', ')} | ${t.description} |\n`;
st += `\n## Choosing a style\n\nThe Director picks: explicit \`style\` in the brief → tone words → industry → wording of the request → audience default (Saudi/Gulf → \`saudi-modern\`, otherwise \`clean-corporate\`). The chosen style and the reason are written to \`plan.json\`.\n\n## Sound effects (${SFX.length} CC0 sounds, ${SFX_CATEGORIES.length} categories)\n\n${SFX_CATEGORIES.map((c) => `\`${c}\``).join(' · ')}\n`;
writeFileSync(join(docs, 'STYLE_LIBRARY.md'), st);
console.log(`docs: ${mods.length} families / ${variants} variants, ${Object.keys(STYLE_PRESETS).length} styles`);
