/**
 * Style library. Each preset is a token set, not a scene: the same scene
 * renders differently under each style. Add a style by adding an entry here
 * (or calling registerStyle) — no engine change needed.
 */
import type { Palette, StyleTokens, DeepPartial } from './tokens';
import { mergeTokens } from './tokens';
import { alpha } from '../brand/color';

function pal(p: Partial<Palette> & Pick<Palette, 'background' | 'primary' | 'textPrimary'>): Palette {
  return {
    backgroundAlt: p.background,
    surface: p.background,
    surfaceAlt: p.background,
    secondary: p.primary,
    accent: p.primary,
    textSecondary: p.textPrimary,
    textOnPrimary: '#FFFFFF',
    textOnSurface: p.textPrimary,
    border: alpha(p.textPrimary, 0.14),
    glow: p.primary,
    positive: '#22C55E',
    negative: '#EF4444',
    ...p,
  };
}

const BASE: StyleTokens = {
  id: 'base',
  name: 'Base',
  description: '',
  mode: 'dark',
  palette: pal({ background: '#0E0F12', primary: '#4C7DFF', textPrimary: '#F5F6F8' }),
  background: { kind: 'soft-gradient', intensity: 0.5, animate: true },
  lighting: 'soft',
  surface: { kind: 'flat', radius: 3.2, borderWidth: 0, blur: 0, opacity: 1 },
  shadow: { strength: 0.35, color: '#000000', spread: 1 },
  glow: 0,
  typography: {
    display: 'ibm-plex-sans-arabic',
    body: 'ibm-plex-sans-arabic',
    latin: 'inter',
    mono: 'jetbrains-mono',
    displayWeight: 700,
    bodyWeight: 400,
    scale: 1,
    lineHeight: 1.35,
    eyebrowCase: 'upper',
    highlight: 'color',
  },
  spacing: { unit: 1, density: 'normal' },
  motion: { intensity: 0.6, easing: 'smooth', entrance: 'rise', stagger: 0.07, float: 0.4, personality: 'tech' },
  transitions: ['crossfade', 'push', 'zoom-in'],
  icon: { style: 'line', stroke: 2 },
  image: { treatment: 'rounded', radius: 3 },
  texture: { grain: 0, vignette: 0.25, scanlines: false },
  depth: 0.5,
  accents: { shape: 'none', amount: 0.3 },
};

const def = (id: string, name: string, description: string, t: DeepPartial<StyleTokens>): StyleTokens => mergeTokens({ ...BASE, id, name, description }, t as Record<string, unknown>);

export const STYLE_PRESETS: Record<string, StyleTokens> = {
  'saudi-modern': def('saudi-modern', 'Saudi Modern', 'Confident deep green + sand gold, geometric calm, GCC digital feel.', {
    mode: 'dark',
    palette: pal({ background: '#0C1612', backgroundAlt: '#0F1F19', surface: '#15261F', surfaceAlt: '#1B3128', primary: '#1FBF75', secondary: '#0F7A4D', accent: '#D9B56C', textPrimary: '#F4F7F5', textSecondary: '#A9BDB3', textOnPrimary: '#04130C', glow: '#1FBF75' }),
    background: { kind: 'geometry', intensity: 0.55, animate: true, secondaryKind: 'atmosphere' },
    lighting: 'key',
    surface: { kind: 'elevated', radius: 3.4, borderWidth: 1, blur: 0, opacity: 1 },
    glow: 0.2,
    typography: { display: 'ibm-plex-sans-arabic', body: 'ibm-plex-sans-arabic', displayWeight: 700, highlight: 'color' },
    motion: { intensity: 0.6, easing: 'smooth', entrance: 'rise', stagger: 0.08, personality: 'tech' },
    transitions: ['push', 'mask-wipe', 'crossfade', 'zoom-in'],
  }),
  'gulf-premium': def('gulf-premium', 'Gulf Premium', 'Midnight navy with warm gold, spotlight depth, slow confident motion.', {
    mode: 'dark',
    palette: pal({ background: '#0A0F1E', backgroundAlt: '#0E1530', surface: '#141C38', surfaceAlt: '#1B2447', primary: '#D4AF6A', secondary: '#8D7443', accent: '#8FB8FF', textPrimary: '#F7F3EA', textSecondary: '#B9B3A5', textOnPrimary: '#16110A', glow: '#D4AF6A' }),
    background: { kind: 'radial-light', intensity: 0.6, animate: true },
    lighting: 'spot',
    surface: { kind: 'elevated', radius: 2.6, borderWidth: 1, blur: 0, opacity: 1 },
    glow: 0.3,
    typography: { display: 'alexandria', body: 'ibm-plex-sans-arabic', displayWeight: 700, latin: 'manrope', highlight: 'color' },
    motion: { intensity: 0.45, easing: 'cinematic', entrance: 'blur', stagger: 0.09, float: 0.3, personality: 'premium' },
    transitions: ['crossfade', 'light-sweep', 'zoom-in', 'blur'],
    texture: { grain: 0.1, vignette: 0.45, scanlines: false },
  }),
  minimal: def('minimal', 'Minimal', 'Off-white canvas, ink type, one warm accent, generous space.', {
    mode: 'light',
    palette: pal({ background: '#F6F5F2', backgroundAlt: '#EFEDE8', surface: '#FFFFFF', surfaceAlt: '#F0EEEA', primary: '#16161A', secondary: '#5B5B63', accent: '#FF5A36', textPrimary: '#121214', textSecondary: '#5E5E66', textOnPrimary: '#FFFFFF', border: '#DEDBD4', glow: '#FF5A36' }),
    background: { kind: 'solid', intensity: 0.3, animate: false },
    lighting: 'flat',
    surface: { kind: 'outline', radius: 2, borderWidth: 2, blur: 0, opacity: 1 },
    shadow: { strength: 0.08, color: '#000000', spread: 0.6 },
    typography: { display: 'ibm-plex-sans-arabic', displayWeight: 600, highlight: 'underline' },
    spacing: { unit: 1.1, density: 'airy' },
    motion: { intensity: 0.4, easing: 'smooth', entrance: 'mask', stagger: 0.08, personality: 'corporate' },
    transitions: ['crossfade', 'slide', 'wipe'],
    texture: { grain: 0, vignette: 0, scanlines: false },
  }),
  'clean-corporate': def('clean-corporate', 'Clean Corporate', 'Trustworthy blue on cool white, structured grid, clear hierarchy.', {
    mode: 'light',
    palette: pal({ background: '#F3F6FB', backgroundAlt: '#E8EEF8', surface: '#FFFFFF', surfaceAlt: '#EEF3FB', primary: '#1D4FE0', secondary: '#0C1F4A', accent: '#18B6A4', textPrimary: '#0C1830', textSecondary: '#4B5A74', textOnPrimary: '#FFFFFF', border: '#D6DFEE' }),
    background: { kind: 'soft-gradient', intensity: 0.4, animate: true, secondaryKind: 'geometry' },
    lighting: 'soft',
    surface: { kind: 'elevated', radius: 2.4, borderWidth: 1, blur: 0, opacity: 1 },
    shadow: { strength: 0.12, color: '#0C1F4A', spread: 1 },
    typography: { display: 'ibm-plex-sans-arabic', displayWeight: 700, highlight: 'color' },
    motion: { intensity: 0.45, easing: 'smooth', entrance: 'rise', personality: 'corporate' },
    transitions: ['push', 'crossfade', 'wipe'],
    texture: { grain: 0, vignette: 0, scanlines: false },
  }),
  saas: def('saas', 'SaaS', 'Soft violet product UI language, floating cards, crisp UI details.', {
    mode: 'light',
    palette: pal({ background: '#F6F5FD', backgroundAlt: '#ECE9FB', surface: '#FFFFFF', surfaceAlt: '#F3F1FE', primary: '#6246EA', secondary: '#2B2C6B', accent: '#12C79A', textPrimary: '#16163A', textSecondary: '#5A5B85', textOnPrimary: '#FFFFFF', border: '#E0DCF6' }),
    background: { kind: 'brand-shapes', intensity: 0.45, animate: true },
    lighting: 'soft',
    surface: { kind: 'soft', radius: 3, borderWidth: 1, blur: 0, opacity: 1 },
    shadow: { strength: 0.16, color: '#2B2C6B', spread: 1.3 },
    typography: { display: 'ibm-plex-sans-arabic', latin: 'inter', displayWeight: 700, highlight: 'marker' },
    motion: { intensity: 0.55, easing: 'snappy', entrance: 'rise', stagger: 0.06, personality: 'tech' },
    transitions: ['push', 'zoom-in', 'slide', 'crossfade'],
    texture: { grain: 0, vignette: 0, scanlines: false },
  }),
  tech: def('tech', 'Tech', 'Dark engineering blue, key light and depth planes, precise outlines and mono details.', {
    mode: 'dark',
    palette: pal({ background: '#070B14', backgroundAlt: '#0B1222', surface: '#0F182B', surfaceAlt: '#132038', primary: '#2F8CFF', secondary: '#1D4E9E', accent: '#00E0C6', textPrimary: '#EAF2FF', textSecondary: '#8EA3C2', textOnPrimary: '#FFFFFF', border: '#1E2F4E', glow: '#2F8CFF' }),
    background: { kind: 'radial-light', intensity: 0.55, animate: true, secondaryKind: 'depth-layers' },
    lighting: 'key',
    surface: { kind: 'outline', radius: 1.6, borderWidth: 1.5, blur: 0, opacity: 0.8 },
    glow: 0.4,
    typography: { display: 'noto-kufi-arabic', body: 'ibm-plex-sans-arabic', latin: 'inter', displayWeight: 700, highlight: 'glow' },
    motion: { intensity: 0.6, easing: 'snappy', entrance: 'wipe', stagger: 0.05, personality: 'tech' },
    transitions: ['mask-wipe', 'push', 'speed-ramp', 'crossfade'],
    icon: { style: 'line', stroke: 1.75 },
  }),
  'ai-futuristic': def('ai-futuristic', 'AI / Futuristic', 'Near-black with violet-cyan aurora, luminous glass, soft glow.', {
    mode: 'dark',
    palette: pal({ background: '#06060D', backgroundAlt: '#0C0A1C', surface: '#12102A', surfaceAlt: '#1A1638', primary: '#8B5CF6', secondary: '#22D3EE', accent: '#F472B6', textPrimary: '#F4F2FF', textSecondary: '#A9A3CC', textOnPrimary: '#FFFFFF', border: '#2A2550', glow: '#8B5CF6' }),
    background: { kind: 'aurora', intensity: 0.7, animate: true, secondaryKind: 'atmosphere' },
    lighting: 'rim',
    surface: { kind: 'glass', radius: 3.2, borderWidth: 1.5, blur: 22, opacity: 0.45 },
    glow: 0.7,
    typography: { display: 'alexandria', body: 'ibm-plex-sans-arabic', latin: 'manrope', displayWeight: 800, highlight: 'glow' },
    motion: { intensity: 0.65, easing: 'cinematic', entrance: 'blur', stagger: 0.07, float: 0.6, personality: 'cinematic' },
    transitions: ['blur', 'zoom-in', 'light-sweep', 'crossfade'],
  }),
  glass: def('glass', 'Glass', 'Frosted glass panels over colourful soft blobs.', {
    mode: 'dark',
    palette: pal({ background: '#0D1326', backgroundAlt: '#141B38', surface: '#1B2446', surfaceAlt: '#232E58', primary: '#5EA8FF', secondary: '#A78BFA', accent: '#F0ABFC', textPrimary: '#F5F8FF', textSecondary: '#B3BEDC', textOnPrimary: '#06122A', glow: '#5EA8FF' }),
    background: { kind: 'glass-depth', intensity: 0.8, animate: true, secondaryKind: 'brand-shapes' },
    lighting: 'soft',
    surface: { kind: 'glass', radius: 3.6, borderWidth: 1.5, blur: 26, opacity: 0.4 },
    glow: 0.35,
    typography: { display: 'ibm-plex-sans-arabic', displayWeight: 700, highlight: 'color' },
    motion: { intensity: 0.55, easing: 'smooth', entrance: 'scale', float: 0.7, personality: 'tech' },
    transitions: ['blur', 'crossfade', 'zoom-in'],
  }),
  neon: def('neon', 'Neon', 'Charcoal night with one electric neon colour and glow.', {
    mode: 'dark',
    palette: pal({ background: '#08080B', backgroundAlt: '#0E0E14', surface: '#121218', surfaceAlt: '#18181F', primary: '#35F28A', secondary: '#16A55A', accent: '#FF3D81', textPrimary: '#F4F4F6', textSecondary: '#9B9BA6', textOnPrimary: '#03140A', border: '#2A2A33', glow: '#35F28A' }),
    background: { kind: 'shadow-field', intensity: 0.55, animate: true, secondaryKind: 'radial-light' },
    lighting: 'rim',
    surface: { kind: 'neon', radius: 2.8, borderWidth: 2, blur: 14, opacity: 0.6 },
    glow: 1,
    typography: { display: 'alexandria', body: 'ibm-plex-sans-arabic', displayWeight: 800, highlight: 'glow' },
    motion: { intensity: 0.7, easing: 'snappy', entrance: 'blur', stagger: 0.06, personality: 'energetic' },
    transitions: ['zoom-in', 'speed-ramp', 'blur', 'mask-wipe'],
    texture: { grain: 0.14, vignette: 0.5, scanlines: false },
  }),
  luxury: def('luxury', 'Luxury', 'Warm black and champagne gold, fine lines, unhurried reveals.', {
    mode: 'dark',
    palette: pal({ background: '#0C0A08', backgroundAlt: '#15110C', surface: '#1A1510', surfaceAlt: '#221B14', primary: '#D8B476', secondary: '#8C6B3F', accent: '#F3E6C8', textPrimary: '#F6EFE2', textSecondary: '#B5A68D', textOnPrimary: '#140F08', border: '#3A2F22', glow: '#D8B476' }),
    background: { kind: 'cinematic-light', intensity: 0.45, animate: true },
    lighting: 'spot',
    surface: { kind: 'outline', radius: 0.6, borderWidth: 1, blur: 0, opacity: 1 },
    glow: 0.2,
    typography: { display: 'noto-kufi-arabic', body: 'noto-sans-arabic', latin: 'manrope', displayWeight: 600, bodyWeight: 400, lineHeight: 1.45, highlight: 'color' },
    spacing: { unit: 1.15, density: 'airy' },
    motion: { intensity: 0.35, easing: 'cinematic', entrance: 'mask', stagger: 0.12, float: 0.2, personality: 'premium' },
    transitions: ['crossfade', 'light-sweep', 'blur'],
    texture: { grain: 0.12, vignette: 0.55, scanlines: false },
  }),
  sports: def('sports', 'Sports', 'High-contrast black, hot red + yellow, diagonal energy, hard cuts.', {
    mode: 'dark',
    palette: pal({ background: '#0A0A0A', backgroundAlt: '#141414', surface: '#1A1A1A', surfaceAlt: '#232323', primary: '#FF3B1F', secondary: '#B3200C', accent: '#FFD400', textPrimary: '#FFFFFF', textSecondary: '#BDBDBD', textOnPrimary: '#FFFFFF', border: '#333333', glow: '#FF3B1F' }),
    background: { kind: 'directional-gradient', intensity: 0.7, animate: true },
    lighting: 'key',
    surface: { kind: 'flat', radius: 0.8, borderWidth: 0, blur: 0, opacity: 1 },
    typography: { display: 'changa', body: 'cairo', latin: 'anton', displayWeight: 800, bodyWeight: 600, lineHeight: 1.25, highlight: 'box' },
    motion: { intensity: 0.9, easing: 'snappy', entrance: 'slide', stagger: 0.04, personality: 'sport' },
    transitions: ['speed-ramp', 'push', 'wipe', 'cut'],
  }),
  ecommerce: def('ecommerce', 'E-commerce', 'Warm, friendly retail: cream, orange, rounded product cards.', {
    mode: 'light',
    palette: pal({ background: '#FFF6EE', backgroundAlt: '#FFEBDB', surface: '#FFFFFF', surfaceAlt: '#FFF1E6', primary: '#F2541B', secondary: '#1F1A17', accent: '#FFB627', textPrimary: '#1C1714', textSecondary: '#6B5E55', textOnPrimary: '#FFFFFF', border: '#F1DCCB' }),
    background: { kind: 'soft-gradient', intensity: 0.5, animate: true, secondaryKind: 'brand-shapes' },
    lighting: 'soft',
    surface: { kind: 'soft', radius: 3.6, borderWidth: 0, blur: 0, opacity: 1 },
    shadow: { strength: 0.14, color: '#7A3A12', spread: 1.2 },
    typography: { display: 'tajawal', body: 'tajawal', latin: 'manrope', displayWeight: 800, bodyWeight: 500, highlight: 'marker' },
    motion: { intensity: 0.7, easing: 'elastic', entrance: 'pop', stagger: 0.06, personality: 'energetic' },
    transitions: ['push', 'zoom-in', 'slide', 'color-sweep'],
    texture: { grain: 0, vignette: 0, scanlines: false },
  }),
  editorial: def('editorial', 'Editorial', 'Magazine paper, strong ink headlines, red rule accents.', {
    mode: 'light',
    palette: pal({ background: '#F1ECE3', backgroundAlt: '#E8E1D5', surface: '#FAF7F1', surfaceAlt: '#EFE9DE', primary: '#141414', secondary: '#4A4540', accent: '#D1402A', textPrimary: '#141414', textSecondary: '#5A544D', textOnPrimary: '#FAF7F1', border: '#CFC6B8' }),
    background: { kind: 'editorial', intensity: 0.5, animate: false, secondaryKind: 'paper' },
    lighting: 'flat',
    surface: { kind: 'paper', radius: 0.4, borderWidth: 1.5, blur: 0, opacity: 1 },
    shadow: { strength: 0.1, color: '#3A2E20', spread: 0.8 },
    typography: { display: 'noto-kufi-arabic', body: 'noto-sans-arabic', displayWeight: 800, lineHeight: 1.3, highlight: 'underline' },
    motion: { intensity: 0.45, easing: 'smooth', entrance: 'mask', stagger: 0.1, personality: 'premium' },
    transitions: ['wipe', 'slide', 'crossfade'],
    texture: { grain: 0.1, vignette: 0.15, scanlines: false },
  }),
  comic: def('comic', 'Comic', 'Pop-art colour blocks, thick outlines, offset shadows, bouncy motion (halftone only on request).', {
    mode: 'light',
    palette: pal({ background: '#FFE9A8', backgroundAlt: '#FFD86B', surface: '#FFFFFF', surfaceAlt: '#FFF6DA', primary: '#E8322E', secondary: '#141414', accent: '#1F6FEB', textPrimary: '#141414', textSecondary: '#3B3B3B', textOnPrimary: '#FFFFFF', border: '#141414' }),
    background: { kind: 'brand-solid', intensity: 0.6, animate: true, secondaryKind: 'directional-gradient' },
    lighting: 'flat',
    surface: { kind: 'comic', radius: 1.8, borderWidth: 4, blur: 0, opacity: 1 },
    shadow: { strength: 1, color: '#141414', spread: 0 },
    typography: { display: 'cairo', body: 'cairo', latin: 'anton', displayWeight: 900, bodyWeight: 700, lineHeight: 1.25, highlight: 'box' },
    motion: { intensity: 0.85, easing: 'elastic', entrance: 'pop', stagger: 0.05, personality: 'playful' },
    transitions: ['zoom-in', 'push', 'iris', 'cut'],
    texture: { grain: 0, vignette: 0, scanlines: false },
  }),
  cinematic: def('cinematic', 'Cinematic', 'Letterboxed film look, warm key light, grain, slow camera.', {
    mode: 'dark',
    palette: pal({ background: '#060608', backgroundAlt: '#0D0D12', surface: '#131318', surfaceAlt: '#1A1A21', primary: '#E9C27E', secondary: '#9A7B45', accent: '#5FA8FF', textPrimary: '#F2EEE6', textSecondary: '#A7A198', textOnPrimary: '#130E06', border: '#2A2A30', glow: '#E9C27E' }),
    background: { kind: 'rays', intensity: 0.55, animate: true },
    lighting: 'key',
    surface: { kind: 'elevated', radius: 1.2, borderWidth: 0, blur: 0, opacity: 1 },
    glow: 0.25,
    typography: { display: 'alexandria', body: 'ibm-plex-sans-arabic', latin: 'manrope', displayWeight: 700, lineHeight: 1.3, highlight: 'color' },
    motion: { intensity: 0.45, easing: 'cinematic', entrance: 'blur', stagger: 0.12, float: 0.25, personality: 'cinematic' },
    transitions: ['crossfade', 'light-sweep', 'blur', 'zoom-out'],
    texture: { grain: 0.12, vignette: 0.7, scanlines: false },
    depth: 0.8,
  }),
  'bold-social': def('bold-social', 'Bold Social', 'Loud lime on black, huge type, punchy pops for feeds.', {
    mode: 'dark',
    palette: pal({ background: '#0D0D0D', backgroundAlt: '#161616', surface: '#1C1C1C', surfaceAlt: '#262626', primary: '#C6FF3D', secondary: '#7ACC00', accent: '#FF4FD8', textPrimary: '#FFFFFF', textSecondary: '#B8B8B8', textOnPrimary: '#0D0D0D', border: '#333333', glow: '#C6FF3D' }),
    background: { kind: 'directional-gradient', intensity: 0.45, animate: true },
    lighting: 'flat',
    surface: { kind: 'flat', radius: 2.4, borderWidth: 0, blur: 0, opacity: 1 },
    typography: { display: 'cairo', body: 'cairo', latin: 'anton', displayWeight: 900, bodyWeight: 600, lineHeight: 1.2, highlight: 'box' },
    motion: { intensity: 0.9, easing: 'snappy', entrance: 'pop', stagger: 0.05, personality: 'energetic' },
    transitions: ['zoom-in', 'push', 'cut', 'speed-ramp'],
  }),
  'dark-premium': def('dark-premium', 'Dark Premium', 'Graphite with periwinkle light, refined elevated cards.', {
    mode: 'dark',
    palette: pal({ background: '#0E0F13', backgroundAlt: '#14161C', surface: '#1A1D25', surfaceAlt: '#222631', primary: '#8EA6FF', secondary: '#4A5BA8', accent: '#D6B4FF', textPrimary: '#F2F3F7', textSecondary: '#9EA3B5', textOnPrimary: '#0B0E1A', border: '#2A2E3A', glow: '#8EA6FF' }),
    background: { kind: 'atmosphere', intensity: 0.5, animate: true },
    lighting: 'soft',
    surface: { kind: 'elevated', radius: 2.8, borderWidth: 1, blur: 0, opacity: 1 },
    glow: 0.25,
    typography: { display: 'ibm-plex-sans-arabic', latin: 'manrope', displayWeight: 600, highlight: 'color' },
    motion: { intensity: 0.5, easing: 'smooth', entrance: 'blur', stagger: 0.08, personality: 'premium' },
    transitions: ['crossfade', 'blur', 'push'],
    texture: { grain: 0.1, vignette: 0.4, scanlines: false },
  }),
  'light-premium': def('light-premium', 'Light Premium', 'Warm ivory, soft shadows, bronze accent, quiet elegance.', {
    mode: 'light',
    palette: pal({ background: '#FAF8F4', backgroundAlt: '#F2EEE7', surface: '#FFFFFF', surfaceAlt: '#F6F2EC', primary: '#1F1D1A', secondary: '#6F6558', accent: '#A8834C', textPrimary: '#1B1916', textSecondary: '#6A635A', textOnPrimary: '#FFFFFF', border: '#E6DFD3' }),
    background: { kind: 'soft-gradient', intensity: 0.35, animate: true, secondaryKind: 'light-sweep' },
    lighting: 'soft',
    surface: { kind: 'elevated', radius: 2.6, borderWidth: 0, blur: 0, opacity: 1 },
    shadow: { strength: 0.1, color: '#4A3A22', spread: 1.4 },
    typography: { display: 'alexandria', body: 'ibm-plex-sans-arabic', latin: 'manrope', displayWeight: 600, highlight: 'underline' },
    spacing: { unit: 1.1, density: 'airy' },
    motion: { intensity: 0.4, easing: 'cinematic', entrance: 'mask', stagger: 0.1, personality: 'premium' },
    transitions: ['crossfade', 'wipe', 'blur'],
    texture: { grain: 0.04, vignette: 0.1, scanlines: false },
  }),
  'product-commercial': def('product-commercial', 'Product Commercial', 'Studio product stage: floor light, soft shadow, hero product first, few words.', {
    mode: 'dark',
    palette: pal({ background: '#0D0E10', backgroundAlt: '#15171B', surface: '#1A1C21', surfaceAlt: '#22252B', primary: '#F2F2F0', secondary: '#8A8F98', accent: '#E7B566', textPrimary: '#F7F7F5', textSecondary: '#A4A8B0', textOnPrimary: '#0D0E10', border: '#2B2E35', glow: '#E7B566' }),
    background: { kind: 'product-stage', intensity: 0.6, animate: true },
    lighting: 'spot',
    surface: { kind: 'elevated', radius: 2, borderWidth: 0, blur: 0, opacity: 1 },
    shadow: { strength: 0.5, color: '#000000', spread: 1.4 },
    typography: { display: 'alexandria', body: 'ibm-plex-sans-arabic', latin: 'manrope', displayWeight: 700, highlight: 'color' },
    spacing: { unit: 1.1, density: 'airy' },
    motion: { intensity: 0.5, easing: 'cinematic', entrance: 'blur', stagger: 0.1, float: 0.3, personality: 'premium' },
    transitions: ['crossfade', 'light-sweep', 'zoom-in', 'blur'],
    texture: { grain: 0.06, vignette: 0.45, scanlines: false },
    depth: 0.8,
  }),
  'app-launch': def('app-launch', 'App Launch', 'Bright launch energy: device-first, brand colour wash, crisp UI micro-interactions.', {
    mode: 'light',
    palette: pal({ background: '#F4F6FF', backgroundAlt: '#E9EDFF', surface: '#FFFFFF', surfaceAlt: '#EEF1FF', primary: '#3B5BFD', secondary: '#0E1A4D', accent: '#FF8A3D', textPrimary: '#0E1430', textSecondary: '#4E5675', textOnPrimary: '#FFFFFF', border: '#DCE2F7' }),
    background: { kind: 'directional-gradient', intensity: 0.55, animate: true, secondaryKind: 'geometry' },
    lighting: 'soft',
    surface: { kind: 'soft', radius: 3.2, borderWidth: 1, blur: 0, opacity: 1 },
    shadow: { strength: 0.16, color: '#0E1A4D', spread: 1.3 },
    typography: { display: 'ibm-plex-sans-arabic', latin: 'inter', displayWeight: 700, highlight: 'marker' },
    motion: { intensity: 0.65, easing: 'snappy', entrance: 'rise', stagger: 0.05, personality: 'tech' },
    transitions: ['push', 'zoom-in', 'mask-wipe', 'slide'],
    texture: { grain: 0, vignette: 0, scanlines: false },
  }),
  'data-storytelling': def('data-storytelling', 'Data Storytelling', 'Calm editorial data: one highlight colour, quiet greys, numbers carry the story.', {
    mode: 'light',
    palette: pal({ background: '#F7F7F4', backgroundAlt: '#EEEEE9', surface: '#FFFFFF', surfaceAlt: '#F1F1EC', primary: '#0F6E5C', secondary: '#2D3A3A', accent: '#E0632E', textPrimary: '#151A1A', textSecondary: '#5A6363', textOnPrimary: '#FFFFFF', border: '#DDDDD5' }),
    background: { kind: 'solid', intensity: 0.3, animate: false, secondaryKind: 'editorial' },
    lighting: 'flat',
    surface: { kind: 'outline', radius: 1.4, borderWidth: 1, blur: 0, opacity: 1 },
    shadow: { strength: 0.06, color: '#000000', spread: 0.6 },
    typography: { display: 'ibm-plex-sans-arabic', body: 'ibm-plex-sans-arabic', latin: 'inter', displayWeight: 700, highlight: 'color' },
    spacing: { unit: 1.05, density: 'airy' },
    motion: { intensity: 0.45, easing: 'smooth', entrance: 'wipe', stagger: 0.07, float: 0, personality: 'corporate' },
    transitions: ['push', 'wipe', 'crossfade'],
    texture: { grain: 0, vignette: 0, scanlines: false },
  }),
};

export const STYLE_IDS = () => Object.keys(STYLE_PRESETS);

export function registerStyle(tokens: StyleTokens): void {
  STYLE_PRESETS[tokens.id] = tokens;
}

/** Friendly aliases the Director / users may use. */
export const STYLE_ALIASES: Record<string, string> = {
  futuristic: 'ai-futuristic',
  ai: 'ai-futuristic',
  corporate: 'clean-corporate',
  'e-commerce': 'ecommerce',
  store: 'ecommerce',
  premium: 'dark-premium',
  gulf: 'gulf-premium',
  saudi: 'saudi-modern',
  social: 'bold-social',
  film: 'cinematic',
  product: 'product-commercial',
  commercial: 'product-commercial',
  launch: 'app-launch',
  'app': 'app-launch',
  data: 'data-storytelling',
  'data-story': 'data-storytelling',
  infographic: 'data-storytelling',
  'saudi-modern': 'saudi-modern',
  'ai-futuristic': 'ai-futuristic',
  'sports': 'sports',
  sport: 'sports',
  'dark': 'dark-premium',
  'light': 'light-premium',
};

export function findStyleId(id: string | undefined): string | undefined {
  if (!id) return undefined;
  const k = id.trim().toLowerCase().replace(/[\s_/]+/g, '-');
  if (STYLE_PRESETS[k]) return k;
  if (STYLE_ALIASES[k]) return STYLE_ALIASES[k];
  return undefined;
}
